Revert "Update flake.lock"
This reverts commit 880c5da1872b0d535ae2f0a087966b70cf99c7ba.

There is something going on with this recent update, future me figure
out:

$ CHECK=no rebuild --show-trace                   +1 masterNM ~/src/pub/github.com/mitc[1465/1847]
warning: Git tree '/Users/mitch/src/pub/github.com/mitchty/nix' is dirty
building the system configuration...
warning: Git tree '/Users/mitch/src/pub/github.com/mitchty/nix' is dirty
error: anonymous function at /nix/store/yxw7g01b90m27jpf8v75gpwdmzkq2iwp-source/pkgs/top-level/ema
cs-packages.nix:58:53 called with unexpected argument 'elpaDevelPackages'

       at /nix/store/yxw7g01b90m27jpf8v75gpwdmzkq2iwp-source/lib/customisation.nix:72:16:

           71|     let
           72|       result = f origArgs;
             |                ^
           73|

       … while evaluating 'makeOverridable'

       at /nix/store/yxw7g01b90m27jpf8v75gpwdmzkq2iwp-source/lib/customisation.nix:70:24:

           69|   */
           70|   makeOverridable = f: origArgs:
             |                        ^
           71|     let